[workspace]

members = [ 
"babelfont-rs",
"ufo-decompose",
"designspace",
"dschecker",
"fonticulus",
"fonttools-cli",
"fonttools-rs",
"openstep-plist",
"otmath",
"otspec",
"otspec_macros",
"triangulate"
]

