[workspace]

members = [ ".", "crates/otspec", "crates/otspec_macros", "crates/fonttools-cli" ]

[package]
name = "fonttools"
version = "0.1.0"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
chrono = { version = "0.4.3" }
otspec = { path = "crates/otspec" } 
otspec_macros = { path = "crates/otspec_macros" } 
indexmap = { version = "1" }
