[workspace]

members = [ ".", "crates/otspec", "crates/otspec_macros", "crates/fonttools-cli", "crates/designspace" ]

[package]
name = "fonttools"
version = "0.1.0"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.3" }
otspec = { path = "crates/otspec" } 
otspec_macros = { path = "crates/otspec_macros" } 
kurbo = { version = "0.8.1" }
bitflags = "1.2.1"
itertools = "0.10.0"
encoding = "0.2"
log = "0.4"
env_logger = "0.8"

[dev-dependencies]
serde_json = { version = "1.0" }
assert_approx_eq = "1.1.0"
