[package]
name = "otmath"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
description = "Mathematical operations useful for OpenType fonts"
repository = "https://github.com/simoncozens/rust-font-tools"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
