[package]
name = "fonttools-cli"
version = "0.1.0"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
edition = "2018"

[dependencies]
fonttools = { path = "../.." }
structopt = "0.3"
itertools = "0.10.0"

[[bin]]
name="ttf-fix-checksum"

[[bin]]
name="ttf-rename-glyphs"
