[package]
name = "fonttools_cli"
version = "0.1.0"
authors = ["Simon Cozens <simon@simon-cozens.org>"]
edition = "2018"

[dependencies]
fonttools = { path = "../.." }
clap = "2.33.3"
itertools = "0.10.0"
skia-safe = "0"
norad = "0.3.1"
lyon = "0.11.0"
kurbo = { version = "0.8.1" }
